<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Order;
use App\Models\Product;
use App\Models\ProductReview;
use App\Models\SystemNotification;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::query()->create([
            'name' => 'Admin Aqlaya',
            'email' => 'admin@aqlaya.test',
            'phone' => '081200000001',
            'address' => 'Jl. Raya Aqlaya No. 17, Bandung',
            'role' => 'admin',
            'is_approved' => true,
            'approved_at' => now(),
            'api_token' => Str::random(60),
            'password' => Hash::make('password'),
        ]);

        $customer = User::query()->create([
            'name' => 'Aya Customer',
            'email' => 'customer@aqlaya.test',
            'phone' => '081200000002',
            'address' => 'Jl. Melati No. 20, Bandung',
            'role' => 'customer',
            'is_approved' => true,
            'approved_at' => now(),
            'api_token' => Str::random(60),
            'password' => Hash::make('password'),
        ]);

        $categories = collect([
            ['name' => 'Cakes', 'slug' => 'cakes', 'description' => 'Cake custom untuk momen spesial.'],
            ['name' => 'Bread', 'slug' => 'bread', 'description' => 'Roti segar panggang setiap hari.'],
            ['name' => 'Pastry', 'slug' => 'pastry', 'description' => 'Pastry buttery untuk sajian.'],
            ['name' => 'Dessert', 'slug' => 'dessert', 'description' => 'Dessert manis penutup hidangan.'],
        ])->mapWithKeys(fn ($category) => [
            $category['slug'] => Category::query()->create($category),
        ]);

        $products = collect([
            // Cakes
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Butter Cake',
                'slug' => 'butter-cake',
                'excerpt' => 'Deskripsi singkat untuk Butter Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Butter Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 177000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Fruit Cake',
                'slug' => 'fruit-cake',
                'excerpt' => 'Deskripsi singkat untuk Fruit Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Fruit Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 277000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Birthday Cake Custom',
                'slug' => 'birthday-cake-custom',
                'excerpt' => 'Deskripsi singkat untuk Birthday Cake Custom.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Birthday Cake Custom yang sangat lezat dan digemari pelanggan.',
                'price' => 238000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Vanilla Cake',
                'slug' => 'vanilla-cake',
                'excerpt' => 'Deskripsi singkat untuk Vanilla Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Vanilla Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 237000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Tiramisu Cake',
                'slug' => 'tiramisu-cake',
                'excerpt' => 'Deskripsi singkat untuk Tiramisu Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Tiramisu Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 167000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Black Forest Cake',
                'slug' => 'black-forest-cake',
                'excerpt' => 'Deskripsi singkat untuk Black Forest Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Black Forest Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 176000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Red Velvet Cake',
                'slug' => 'red-velvet-cake',
                'excerpt' => 'Deskripsi singkat untuk Red Velvet Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Red Velvet Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 299000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Matcha Opera Cake',
                'slug' => 'matcha-opera-cake',
                'excerpt' => 'Deskripsi singkat untuk Matcha Opera Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Matcha Opera Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 240000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Lemon Meringue Cake',
                'slug' => 'lemon-meringue-cake',
                'excerpt' => 'Deskripsi singkat untuk Lemon Meringue Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Lemon Meringue Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 232000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['cakes']->id,
                'name' => 'Choco Lava Cake',
                'slug' => 'choco-lava-cake',
                'excerpt' => 'Deskripsi singkat untuk Choco Lava Cake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Choco Lava Cake yang sangat lezat dan digemari pelanggan.',
                'price' => 234000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            // Bread
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Coklat',
                'slug' => 'roti-coklat',
                'excerpt' => 'Deskripsi singkat untuk Roti Coklat.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Coklat yang sangat lezat dan digemari pelanggan.',
                'price' => 39000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Donat',
                'slug' => 'donat',
                'excerpt' => 'Deskripsi singkat untuk Donat.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Donat yang sangat lezat dan digemari pelanggan.',
                'price' => 37000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Pizza',
                'slug' => 'pizza',
                'excerpt' => 'Deskripsi singkat untuk Pizza.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Pizza yang sangat lezat dan digemari pelanggan.',
                'price' => 43000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Sisir',
                'slug' => 'roti-sisir',
                'excerpt' => 'Deskripsi singkat untuk Roti Sisir.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Sisir yang sangat lezat dan digemari pelanggan.',
                'price' => 26000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Abon',
                'slug' => 'roti-abon',
                'excerpt' => 'Deskripsi singkat untuk Roti Abon.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Abon yang sangat lezat dan digemari pelanggan.',
                'price' => 49000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Susu Hokkaido',
                'slug' => 'roti-susu-hokkaido',
                'excerpt' => 'Deskripsi singkat untuk Roti Susu Hokkaido.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Susu Hokkaido yang sangat lezat dan digemari pelanggan.',
                'price' => 40000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Keju Lumer',
                'slug' => 'roti-keju-lumer',
                'excerpt' => 'Deskripsi singkat untuk Roti Keju Lumer.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Keju Lumer yang sangat lezat dan digemari pelanggan.',
                'price' => 33000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Sosis',
                'slug' => 'roti-sosis',
                'excerpt' => 'Deskripsi singkat untuk Roti Sosis.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Sosis yang sangat lezat dan digemari pelanggan.',
                'price' => 28000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Kopi Goreng',
                'slug' => 'roti-kopi-goreng',
                'excerpt' => 'Deskripsi singkat untuk Roti Kopi Goreng.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Kopi Goreng yang sangat lezat dan digemari pelanggan.',
                'price' => 43000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['bread']->id,
                'name' => 'Roti Pandan Srikaya',
                'slug' => 'roti-pandan-srikaya',
                'excerpt' => 'Deskripsi singkat untuk Roti Pandan Srikaya.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Roti Pandan Srikaya yang sangat lezat dan digemari pelanggan.',
                'price' => 28000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            // Pastry
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Croissant',
                'slug' => 'croissant',
                'excerpt' => 'Deskripsi singkat untuk Croissant.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Croissant yang sangat lezat dan digemari pelanggan.',
                'price' => 47000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Danish Strawberry',
                'slug' => 'danish-strawberry',
                'excerpt' => 'Deskripsi singkat untuk Danish Strawberry.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Danish Strawberry yang sangat lezat dan digemari pelanggan.',
                'price' => 36000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Danish Chocolate',
                'slug' => 'danish-chocolate',
                'excerpt' => 'Deskripsi singkat untuk Danish Chocolate.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Danish Chocolate yang sangat lezat dan digemari pelanggan.',
                'price' => 44000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Cheese Puff',
                'slug' => 'cheese-puff',
                'excerpt' => 'Deskripsi singkat untuk Cheese Puff.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Cheese Puff yang sangat lezat dan digemari pelanggan.',
                'price' => 40000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Almond Croissant',
                'slug' => 'almond-croissant',
                'excerpt' => 'Deskripsi singkat untuk Almond Croissant.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Almond Croissant yang sangat lezat dan digemari pelanggan.',
                'price' => 50000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Pain au Chocolat',
                'slug' => 'pain-au-chocolat',
                'excerpt' => 'Deskripsi singkat untuk Pain au Chocolat.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Pain au Chocolat yang sangat lezat dan digemari pelanggan.',
                'price' => 20000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Kouign-Amann',
                'slug' => 'kouign-amann',
                'excerpt' => 'Deskripsi singkat untuk Kouign-Amann.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Kouign-Amann yang sangat lezat dan digemari pelanggan.',
                'price' => 30000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Apple Strudel',
                'slug' => 'apple-strudel',
                'excerpt' => 'Deskripsi singkat untuk Apple Strudel.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Apple Strudel yang sangat lezat dan digemari pelanggan.',
                'price' => 27000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Cinnamon Roll',
                'slug' => 'cinnamon-roll',
                'excerpt' => 'Deskripsi singkat untuk Cinnamon Roll.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Cinnamon Roll yang sangat lezat dan digemari pelanggan.',
                'price' => 22000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['pastry']->id,
                'name' => 'Beef Sausage Roll',
                'slug' => 'beef-sausage-roll',
                'excerpt' => 'Deskripsi singkat untuk Beef Sausage Roll.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Beef Sausage Roll yang sangat lezat dan digemari pelanggan.',
                'price' => 37000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            // Dessert
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Cheesecake',
                'slug' => 'cheesecake',
                'excerpt' => 'Deskripsi singkat untuk Cheesecake.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Cheesecake yang sangat lezat dan digemari pelanggan.',
                'price' => 23000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Tiramisu Cup',
                'slug' => 'tiramisu-cup',
                'excerpt' => 'Deskripsi singkat untuk Tiramisu Cup.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Tiramisu Cup yang sangat lezat dan digemari pelanggan.',
                'price' => 27000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Pudding Cokelat',
                'slug' => 'pudding-cokelat',
                'excerpt' => 'Deskripsi singkat untuk Pudding Cokelat.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Pudding Cokelat yang sangat lezat dan digemari pelanggan.',
                'price' => 30000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => true,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Panna Cotta',
                'slug' => 'panna-cotta',
                'excerpt' => 'Deskripsi singkat untuk Panna Cotta.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Panna Cotta yang sangat lezat dan digemari pelanggan.',
                'price' => 48000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Dessert Box (cokelat/oreo)',
                'slug' => 'dessert-box-cokelat-oreo',
                'excerpt' => 'Deskripsi singkat untuk Dessert Box (cokelat/oreo).',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Dessert Box (cokelat/oreo) yang sangat lezat dan digemari pelanggan.',
                'price' => 32000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Banana Dessert',
                'slug' => 'banana-dessert',
                'excerpt' => 'Deskripsi singkat untuk Banana Dessert.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Banana Dessert yang sangat lezat dan digemari pelanggan.',
                'price' => 24000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Macaron Box',
                'slug' => 'macaron-box',
                'excerpt' => 'Deskripsi singkat untuk Macaron Box.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Macaron Box yang sangat lezat dan digemari pelanggan.',
                'price' => 32000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Choco Mousse Cup',
                'slug' => 'choco-mousse-cup',
                'excerpt' => 'Deskripsi singkat untuk Choco Mousse Cup.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Choco Mousse Cup yang sangat lezat dan digemari pelanggan.',
                'price' => 35000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Mango Sago',
                'slug' => 'mango-sago',
                'excerpt' => 'Deskripsi singkat untuk Mango Sago.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Mango Sago yang sangat lezat dan digemari pelanggan.',
                'price' => 50000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_id' => $categories['dessert']->id,
                'name' => 'Creme Brulee',
                'slug' => 'creme-brulee',
                'excerpt' => 'Deskripsi singkat untuk Creme Brulee.',
                'description' => 'Ini adalah deskripsi lengkap untuk produk Creme Brulee yang sangat lezat dan digemari pelanggan.',
                'price' => 20000,
                'stock' => 20,
                'is_active' => true,
                'is_best_seller' => false,
                'sizes' => ['Regular'],
                'image_url' => 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
            ],
        ])->mapWithKeys(fn ($product) => [
            $product['slug'] => Product::query()->create($product),
        ]);

        $completedOrder = Order::query()->create([
            'user_id' => $customer->id,
            'order_code' => 'AQL-DEMO-001',
            'status' => Order::STATUS_COMPLETED,
            'payment_status' => Order::PAYMENT_PAID,
            'shipping_method' => 'pickup',
            'customer_name' => $customer->name,
            'customer_email' => $customer->email,
            'customer_phone' => $customer->phone,
            'scheduled_for' => Carbon::now()->subDay(),
            'message_on_cake' => 'Happy Birthday Aya',
            'subtotal' => 610000,
            'delivery_fee' => 0,
            'total_amount' => 610000,
            'midtrans_reference' => 'SIM-AQL-DEMO-001',
            'paid_at' => Carbon::now()->subDays(3),
            'completed_at' => Carbon::now()->subDay(),
        ]);

        $completedOrder->items()->createMany([
            [
                'product_id' => $products['butter-cake']->id,
                'product_name' => $products['butter-cake']->name,
                'product_price' => $products['butter-cake']->price,
                'size' => 'Diameter 16 cm',
                'quantity' => 1,
                'scheduled_date' => Carbon::now()->subDay()->toDateString(),
                'scheduled_time' => '11:00',
                'custom_message' => 'Happy Birthday Aya',
                'notes' => 'Warna pink lembut.',
                'line_total' => 285000,
            ],
            [
                'product_id' => $products['fruit-cake']->id,
                'product_name' => $products['fruit-cake']->name,
                'product_price' => $products['fruit-cake']->price,
                'size' => 'Diameter 18 cm',
                'quantity' => 1,
                'scheduled_date' => Carbon::now()->subDay()->toDateString(),
                'scheduled_time' => '11:30',
                'custom_message' => 'Best Team Ever',
                'notes' => 'Tanpa kacang.',
                'line_total' => 325000,
            ],
        ]);

        ProductReview::query()->create([
            'product_id' => $products['butter-cake']->id,
            'user_id' => $customer->id,
            'order_id' => $completedOrder->id,
            'rating' => 5,
            'review' => 'Dekor cantik dan rasa fresh. Proses order sampai pickup terasa jelas statusnya.',
        ]);

        $awaitingOrder = Order::query()->create([
            'user_id' => $customer->id,
            'order_code' => 'AQL-DEMO-002',
            'status' => Order::STATUS_AWAITING_CONFIRMATION,
            'payment_status' => Order::PAYMENT_PAID,
            'shipping_method' => 'delivery',
            'customer_name' => $customer->name,
            'customer_email' => $customer->email,
            'customer_phone' => $customer->phone,
            'delivery_address' => $customer->address,
            'scheduled_for' => Carbon::now()->addDays(3)->setTime(14, 0),
            'message_on_cake' => 'Congrats on Launch Day',
            'order_notes' => 'Mohon telepon 15 menit sebelum tiba.',
            'subtotal' => 440000,
            'delivery_fee' => 25000,
            'total_amount' => 465000,
            'midtrans_reference' => 'SIM-AQL-DEMO-002',
            'paid_at' => Carbon::now()->subHours(5),
        ]);

        $awaitingOrder->items()->create([
            'product_id' => $products['birthday-cake-custom']->id,
            'product_name' => $products['birthday-cake-custom']->name,
            'product_price' => $products['birthday-cake-custom']->price,
            'size' => 'Diameter 20 cm',
            'quantity' => 1,
            'scheduled_date' => Carbon::now()->addDays(3)->toDateString(),
            'scheduled_time' => '14:00',
            'custom_message' => 'Congrats on Launch Day',
            'notes' => 'Tambahkan kartu ucapan.',
            'line_total' => 295000,
        ]);

        $awaitingOrder->items()->create([
            'product_id' => $products['cheesecake']->id,
            'product_name' => $products['cheesecake']->name,
            'product_price' => $products['cheesecake']->price,
            'size' => 'Box Premium',
            'quantity' => 1,
            'scheduled_date' => Carbon::now()->addDays(3)->toDateString(),
            'scheduled_time' => '14:00',
            'custom_message' => null,
            'notes' => 'Gunakan pita warna rose gold.',
            'line_total' => 145000,
        ]);

        SystemNotification::query()->create([
            'user_id' => $admin->id,
            'title' => 'Pesanan auto-lunas menunggu keputusan',
            'message' => 'Pesanan AQL-DEMO-002 sudah dibayar dan menunggu konfirmasi kapasitas dapur.',
            'action_url' => '/admin/orders/'.$awaitingOrder->id,
        ]);

        SystemNotification::query()->create([
            'user_id' => $customer->id,
            'title' => 'Pembayaran berhasil',
            'message' => 'Pesanan AQL-DEMO-002 sudah dibayar dan menunggu konfirmasi admin.',
            'action_url' => '/orders/'.$awaitingOrder->id,
        ]);
    }
}
